#ifndef FRAMEFLOW_WRITER_GLOBAL_H
#define FRAMEFLOW_WRITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FRAMEFLOW_WRITER_LIBRARY)
#define FRAMEFLOW_WRITER_EXPORT Q_DECL_EXPORT
#else
#define FRAMEFLOW_WRITER_EXPORT Q_DECL_IMPORT
#endif

#endif // FRAMEFLOW_WRITER_GLOBAL_H
